/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import java.text.DecimalFormat;
import java.util.Scanner;

/**
 *
 * @author Familia Pc
 */
public class personas extends javax.swing.JFrame {
Scanner entrada = new Scanner(System.in);
DecimalFormat f = new DecimalFormat("0.00");
    int matriz[][] ={{1,2,1,2,1,1,2,1,1,2},{1,2,1,1,2,1,1,1,1,1},{2500,0,8950,9000,0,5500,3500,3850,7650,6500}};
    
    public personas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt = new javax.swing.JTextField();
        v = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        v.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Promedio del salario de los Hombres que trabajan", "Promedio del salario de las Mujeres que trabajan", "Porcentaje total de Hombres", "Porcentaje total de Mujeres", "Porcentaje total de Hombres que trabajan", "Porcentaje total de Mujeres que trabajan" }));
        v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(v, 0, 274, Short.MAX_VALUE)
                    .addComponent(txt))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(v, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vActionPerformed
     float h = 0,m = 0,th = 0,tm = 0 , ho = 0 , mu = 0,hp =0 ,mp =0;
    
     if(v.getSelectedIndex()==0){
        txt.setText(""); 
     }   
     if(v.getSelectedIndex()==1){
        for(int x=0;x<10;x++){
        if(matriz[0][x]==1){
        ho+=1;
        th+=matriz[2][x];
                }
            }
     txt.setText("$"+f.format(th/ho)); 
     }    
     
     if(v.getSelectedIndex()==2){
        for(int x=0;x<10;x++){
        if(matriz[0][x]==2){
        mu+=1;
        tm+=matriz[2][x];
                }
            }
     txt.setText("$"+f.format(tm/mu));      
         
     }
     if(v.getSelectedIndex()==3){
         for(int x=0;x<10;x++){
         if(matriz[0][x]==1){
         hp+=1;
             
         }
         }
         txt.setText(f.format((hp/10)*100)+"%");
         
     } 
     if(v.getSelectedIndex()==4){
         for(int x=0;x<10;x++){
         if(matriz[0][x]==2){
         mp+=1;
         }
         }
         txt.setText(f.format((mp/10)*100)+"%");
         
         
     } 
     if(v.getSelectedIndex()==5){
       for(int x=0;x<10;x++){
          if(matriz[0][x]==1){
          if(matriz[1][x]==1){
            h+=1;
            }
            }
          }
          
        txt.setText(f.format((h/6)*100)+"%"); 
     } 
     if(v.getSelectedIndex()==6){
       for(int x=0;x<10;x++){
          if(matriz[0][x]==2){
          if(matriz[1][x]==2){
             m+=1;
                       
           }
           }
           }
        txt.setText(f.format((m/4)*100)+"%");
     } 
    }//GEN-LAST:event_vActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(personas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(personas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(personas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(personas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new personas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField txt;
    private javax.swing.JComboBox v;
    // End of variables declaration//GEN-END:variables
}
