
import java.awt.event.ActionEvent;
import javax.swing.DefaultListModel;
import javax.swing.Timer;
import javax.swing.JOptionPane;




/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
public class tiendav extends javax.swing.JFrame {
    String vector[]=new String[15];
    int vectorprec[]=new int[15];
    double Iva[]= new double[15];
    double SinIva[]= new double[15];
    double Viva[]= new double[15];
        double Vsiniva[] = new double[15];
        String GuardarP[] = new String[15];
        int GuardarV[]=new int[15];
        int vectormultiplicacion[]=new int[15];
        int c=0;


DefaultListModel llenarlista = new DefaultListModel();
DefaultListModel llenarlista2 = new DefaultListModel();
DefaultListModel llenarlista3 = new DefaultListModel();
DefaultListModel Producto = new DefaultListModel();
    /** Creates new form tiendav */
    public tiendav() {
        initComponents();
        panel1.setVisible(true);
        panel2.setVisible(false);
        panel3.setVisible(false);
        panel4.setVisible(false);
        panel5.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        FinalC = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        panel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Comprar = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Scvendedor = new javax.swing.JButton();
        panel2 = new javax.swing.JPanel();
        TabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        DolexF = new javax.swing.JCheckBox();
        Pedialyte = new javax.swing.JCheckBox();
        Acetaminofem = new javax.swing.JCheckBox();
        DolexG = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        VitaC = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        Drogueria = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Sdolexf = new javax.swing.JComboBox<String>();
        Spedialyte = new javax.swing.JComboBox<String>();
        Sacetaminofem = new javax.swing.JComboBox<String>();
        Sdolexg = new javax.swing.JComboBox<String>();
        Svitac = new javax.swing.JComboBox<String>();
        jScrollPane7 = new javax.swing.JScrollPane();
        JLista2 = new javax.swing.JList<String>();
        BorrarP2 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        la6 = new javax.swing.JLabel();
        la7 = new javax.swing.JLabel();
        la8 = new javax.swing.JLabel();
        la9 = new javax.swing.JLabel();
        la10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        JabonD = new javax.swing.JCheckBox();
        Desodorante = new javax.swing.JCheckBox();
        Cepillo = new javax.swing.JCheckBox();
        JabonF = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        Crema = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        Aseo = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Sjabond = new javax.swing.JComboBox<String>();
        Sdesodorante = new javax.swing.JComboBox<String>();
        Scepillo = new javax.swing.JComboBox<String>();
        Sjabonf = new javax.swing.JComboBox<String>();
        Screma = new javax.swing.JComboBox<String>();
        jScrollPane6 = new javax.swing.JScrollPane();
        JLista3 = new javax.swing.JList<String>();
        BorrarP3 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        la11 = new javax.swing.JLabel();
        la12 = new javax.swing.JLabel();
        la13 = new javax.swing.JLabel();
        la14 = new javax.swing.JLabel();
        la15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Arroz = new javax.swing.JCheckBox();
        Huevos = new javax.swing.JCheckBox();
        Aceite = new javax.swing.JCheckBox();
        Lentejas = new javax.swing.JCheckBox();
        Leche = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Alimentos = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Sarroz = new javax.swing.JComboBox<String>();
        Shuevos = new javax.swing.JComboBox<String>();
        Saceite = new javax.swing.JComboBox<String>();
        Slentejas = new javax.swing.JComboBox<String>();
        Sleche = new javax.swing.JComboBox<String>();
        jScrollPane5 = new javax.swing.JScrollPane();
        JLista1 = new javax.swing.JList<String>();
        BorrarP1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        la1 = new javax.swing.JLabel();
        la2 = new javax.swing.JLabel();
        la3 = new javax.swing.JLabel();
        la4 = new javax.swing.JLabel();
        la5 = new javax.swing.JLabel();
        FinalizarC = new javax.swing.JButton();
        panel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        producto = new javax.swing.JList<String>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Siniva = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        iva = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        Vtotal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        panel4 = new javax.swing.JPanel();
        Clave = new javax.swing.JButton();
        usuario = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel17 = new javax.swing.JLabel();
        panel5 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        imProducto = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        Mayor = new javax.swing.JTextField();
        Menor = new javax.swing.JTextField();
        TotalV = new javax.swing.JTextField();
        Moda = new javax.swing.JTextField();
        reabastecer = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        volver = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        FinalC.setText("Finalizar Compras");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 693, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        panel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "BIENVENIDOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 36))); // NOI18N
        panel1.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel9.setText("Nueva Tienda Virtual");
        panel1.add(jLabel9);
        jLabel9.setBounds(10, 60, 420, 40);

        Comprar.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        Comprar.setText("COMPRAR");
        Comprar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarActionPerformed(evt);
            }
        });
        panel1.add(Comprar);
        Comprar.setBounds(410, 160, 230, 60);

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel35.setText("Recomendaciones: Si está seguro de sus compras haga clic en finalizar");
        panel1.add(jLabel35);
        jLabel35.setBounds(10, 160, 390, 20);

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel36.setText(" Seleccione la cantidad de productos a comprar");
        panel1.add(jLabel36);
        jLabel36.setBounds(110, 180, 270, 20);

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel37.setText(" Seleccione cada producto para saber su precio");
        panel1.add(jLabel37);
        jLabel37.setBounds(110, 200, 270, 20);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("SI NECESITA REVISAR LA TIENDA VE A:");
        panel1.add(jLabel2);
        jLabel2.setBounds(60, 310, 230, 20);

        Scvendedor.setText("SECCIÓN DEL VENDEDOR");
        Scvendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScvendedorActionPerformed(evt);
            }
        });
        panel1.add(Scvendedor);
        Scvendedor.setBounds(290, 310, 160, 23);

        getContentPane().add(panel1);
        panel1.setBounds(10, 0, 730, 390);

        panel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel2.setLayout(null);

        TabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setLayout(null);

        DolexF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DolexFActionPerformed(evt);
            }
        });
        jPanel4.add(DolexF);
        DolexF.setBounds(240, 70, 40, 21);

        Pedialyte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedialyteActionPerformed(evt);
            }
        });
        jPanel4.add(Pedialyte);
        Pedialyte.setBounds(240, 110, 40, 21);

        Acetaminofem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcetaminofemActionPerformed(evt);
            }
        });
        jPanel4.add(Acetaminofem);
        Acetaminofem.setBounds(240, 140, 40, 21);

        DolexG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DolexGActionPerformed(evt);
            }
        });
        jPanel4.add(DolexG);
        DolexG.setBounds(240, 180, 40, 21);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("PRODUCTO");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(10, 34, 100, 17);

        VitaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VitaCActionPerformed(evt);
            }
        });
        jPanel4.add(VitaC);
        VitaC.setBounds(240, 220, 40, 21);

        jLabel6.setText("INVENTARIO");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(490, 20, 100, 14);

        Drogueria.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(Drogueria);
        Drogueria.setBounds(476, 310, 170, 21);

        jLabel14.setText("Precio Por Unidad");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(344, 320, 110, 14);

        Sdolexf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "1", "2", "3", "4", "5" }));
        Sdolexf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SdolexfActionPerformed(evt);
            }
        });
        jPanel4.add(Sdolexf);
        Sdolexf.setBounds(120, 70, 100, 20);

        Spedialyte.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "1", "2", "3", "4", "5" }));
        Spedialyte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpedialyteActionPerformed(evt);
            }
        });
        jPanel4.add(Spedialyte);
        Spedialyte.setBounds(120, 110, 100, 20);

        Sacetaminofem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "1", "2", "3", "4", "5" }));
        Sacetaminofem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SacetaminofemActionPerformed(evt);
            }
        });
        jPanel4.add(Sacetaminofem);
        Sacetaminofem.setBounds(120, 140, 100, 20);

        Sdolexg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "1", "2", "3", "4", "5" }));
        Sdolexg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SdolexgActionPerformed(evt);
            }
        });
        jPanel4.add(Sdolexg);
        Sdolexg.setBounds(120, 180, 100, 20);

        Svitac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "1", "2", "3", "4", "5" }));
        Svitac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SvitacActionPerformed(evt);
            }
        });
        jPanel4.add(Svitac);
        Svitac.setBounds(120, 220, 100, 20);

        jScrollPane7.setViewportView(JLista2);

        jPanel4.add(jScrollPane7);
        jScrollPane7.setBounds(470, 40, 181, 263);

        BorrarP2.setText("Borrar Producto");
        BorrarP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarP2ActionPerformed(evt);
            }
        });
        jPanel4.add(BorrarP2);
        BorrarP2.setBounds(310, 290, 150, 20);

        jLabel30.setText("Precio P/U");
        jPanel4.add(jLabel30);
        jLabel30.setBounds(240, 40, 70, 14);

        jLabel31.setText("Dolex Forte");
        jPanel4.add(jLabel31);
        jLabel31.setBounds(10, 70, 80, 14);

        jLabel32.setText("Pedialyte Max");
        jPanel4.add(jLabel32);
        jLabel32.setBounds(10, 110, 100, 14);

        jLabel33.setText("Acetaminofem");
        jPanel4.add(jLabel33);
        jLabel33.setBounds(10, 150, 100, 14);

        jLabel34.setText("Dolex Gripa");
        jPanel4.add(jLabel34);
        jLabel34.setBounds(10, 190, 80, 14);

        jLabel38.setText("Vita C Mk");
        jPanel4.add(jLabel38);
        jLabel38.setBounds(10, 220, 70, 14);

        la6.setText("20");
        jPanel4.add(la6);
        la6.setBounds(300, 70, 30, 14);

        la7.setText("20");
        jPanel4.add(la7);
        la7.setBounds(300, 100, 30, 14);

        la8.setText("20");
        jPanel4.add(la8);
        la8.setBounds(300, 140, 30, 14);

        la9.setText("20");
        jPanel4.add(la9);
        la9.setBounds(300, 180, 30, 14);

        la10.setText("20");
        jPanel4.add(la10);
        la10.setBounds(300, 220, 30, 14);

        TabbedPane1.addTab("Droguería", jPanel4);

        jPanel3.setLayout(null);

        JabonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JabonDActionPerformed(evt);
            }
        });
        jPanel3.add(JabonD);
        JabonD.setBounds(270, 60, 21, 21);

        Desodorante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesodoranteActionPerformed(evt);
            }
        });
        jPanel3.add(Desodorante);
        Desodorante.setBounds(270, 100, 21, 21);

        Cepillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CepilloActionPerformed(evt);
            }
        });
        jPanel3.add(Cepillo);
        Cepillo.setBounds(270, 140, 21, 21);

        JabonF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JabonFActionPerformed(evt);
            }
        });
        jPanel3.add(JabonF);
        JabonF.setBounds(270, 180, 21, 21);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("PRODUCTO");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(10, 34, 127, 17);

        Crema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CremaActionPerformed(evt);
            }
        });
        jPanel3.add(Crema);
        Crema.setBounds(270, 220, 20, 21);

        jLabel5.setText("INVENTARIO");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(530, 10, 120, 14);

        Aseo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(Aseo);
        Aseo.setBounds(500, 320, 180, 21);

        jLabel13.setText("Precio Por Unidad");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(354, 320, 120, 14);

        Sjabond.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "1", "2", "3", "4", "5" }));
        Sjabond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SjabondActionPerformed(evt);
            }
        });
        jPanel3.add(Sjabond);
        Sjabond.setBounds(155, 62, 100, 20);

        Sdesodorante.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "1", "2", "3", "4", "5" }));
        Sdesodorante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SdesodoranteActionPerformed(evt);
            }
        });
        jPanel3.add(Sdesodorante);
        Sdesodorante.setBounds(155, 101, 100, 20);

        Scepillo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "1", "2", "3", "4", "5" }));
        Scepillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScepilloActionPerformed(evt);
            }
        });
        jPanel3.add(Scepillo);
        Scepillo.setBounds(155, 140, 100, 20);

        Sjabonf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "1", "2", "3", "4", "5" }));
        Sjabonf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SjabonfActionPerformed(evt);
            }
        });
        jPanel3.add(Sjabonf);
        Sjabonf.setBounds(155, 179, 100, 20);

        Screma.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "1", "2", "3", "4", "5" }));
        Screma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScremaActionPerformed(evt);
            }
        });
        jPanel3.add(Screma);
        Screma.setBounds(155, 218, 100, 20);

        jScrollPane6.setViewportView(JLista3);

        jPanel3.add(jScrollPane6);
        jScrollPane6.setBounds(500, 30, 181, 274);

        BorrarP3.setText("Borrar Producto");
        BorrarP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarP3ActionPerformed(evt);
            }
        });
        jPanel3.add(BorrarP3);
        BorrarP3.setBounds(330, 280, 150, 20);

        jLabel24.setText("Precio P/U");
        jPanel3.add(jLabel24);
        jLabel24.setBounds(260, 40, 80, 14);

        jLabel25.setText("Jabon Dove");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(10, 65, 90, 14);

        jLabel26.setText("Desodorante Balance");
        jPanel3.add(jLabel26);
        jLabel26.setBounds(10, 104, 140, 14);

        jLabel27.setText("Cepillo dental ");
        jPanel3.add(jLabel27);
        jLabel27.setBounds(10, 143, 100, 14);

        jLabel28.setText("Jabon Fab");
        jPanel3.add(jLabel28);
        jLabel28.setBounds(10, 182, 90, 14);

        jLabel29.setText("Crema dental Colgate");
        jPanel3.add(jLabel29);
        jLabel29.setBounds(10, 221, 140, 14);

        la11.setText("20");
        jPanel3.add(la11);
        la11.setBounds(310, 70, 30, 14);

        la12.setText("20");
        jPanel3.add(la12);
        la12.setBounds(310, 110, 30, 14);

        la13.setText("20");
        jPanel3.add(la13);
        la13.setBounds(310, 140, 30, 14);

        la14.setText("20");
        jPanel3.add(la14);
        la14.setBounds(310, 180, 30, 14);

        la15.setText("20");
        jPanel3.add(la15);
        la15.setBounds(310, 220, 30, 14);

        TabbedPane1.addTab("Aseo", jPanel3);

        jPanel1.setLayout(null);

        Arroz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArrozActionPerformed(evt);
            }
        });
        jPanel1.add(Arroz);
        Arroz.setBounds(290, 60, 21, 21);

        Huevos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuevosActionPerformed(evt);
            }
        });
        jPanel1.add(Huevos);
        Huevos.setBounds(290, 100, 21, 21);

        Aceite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceiteActionPerformed(evt);
            }
        });
        jPanel1.add(Aceite);
        Aceite.setBounds(290, 140, 21, 21);

        Lentejas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LentejasActionPerformed(evt);
            }
        });
        jPanel1.add(Lentejas);
        Lentejas.setBounds(290, 180, 21, 21);

        Leche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LecheActionPerformed(evt);
            }
        });
        jPanel1.add(Leche);
        Leche.setBounds(290, 220, 21, 21);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("PRODUCTO");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 34, 81, 17);

        jLabel4.setText("INVENTARIO");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(520, 10, 72, 14);

        Alimentos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(Alimentos);
        Alimentos.setBounds(470, 310, 180, 21);

        jLabel10.setText("Precio Por Unidad");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(314, 310, 140, 14);

        Sarroz.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "1", "2", "3", "4", "5" }));
        Sarroz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SarrozActionPerformed(evt);
            }
        });
        jPanel1.add(Sarroz);
        Sarroz.setBounds(130, 60, 140, 20);

        Shuevos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "1", "2", "3", "4", "5" }));
        Shuevos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShuevosActionPerformed(evt);
            }
        });
        jPanel1.add(Shuevos);
        Shuevos.setBounds(130, 100, 140, 20);

        Saceite.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "1", "2", "3", "4", "5" }));
        Saceite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaceiteActionPerformed(evt);
            }
        });
        jPanel1.add(Saceite);
        Saceite.setBounds(130, 140, 140, 20);

        Slentejas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "1", "2", "3", "4", "5" }));
        Slentejas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SlentejasActionPerformed(evt);
            }
        });
        jPanel1.add(Slentejas);
        Slentejas.setBounds(130, 180, 140, 20);

        Sleche.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "1", "2", "3", "4", "5" }));
        Sleche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SlecheActionPerformed(evt);
            }
        });
        jPanel1.add(Sleche);
        Sleche.setBounds(130, 220, 140, 20);

        jScrollPane5.setViewportView(JLista1);

        jPanel1.add(jScrollPane5);
        jScrollPane5.setBounds(470, 30, 181, 274);

        BorrarP1.setText("Borrar Producto");
        BorrarP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarP1ActionPerformed(evt);
            }
        });
        jPanel1.add(BorrarP1);
        BorrarP1.setBounds(280, 280, 170, 20);

        jLabel18.setText("Precio P/U");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(280, 30, 110, 20);

        jLabel19.setText("Arroz Diana");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(10, 65, 90, 14);

        jLabel20.setText("Huevos");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(10, 104, 70, 14);

        jLabel21.setText("Lentejas");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(10, 176, 70, 14);

        jLabel22.setText("Leche Alqueria");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(10, 215, 100, 14);

        jLabel23.setText("Aceite Oliosoya");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(10, 143, 110, 14);

        la1.setText("20");
        jPanel1.add(la1);
        la1.setBounds(330, 70, 30, 14);

        la2.setText("20");
        jPanel1.add(la2);
        la2.setBounds(330, 110, 40, 14);

        la3.setText("20");
        jPanel1.add(la3);
        la3.setBounds(330, 150, 30, 14);

        la4.setText("20");
        jPanel1.add(la4);
        la4.setBounds(330, 190, 50, 14);

        la5.setText("20");
        jPanel1.add(la5);
        la5.setBounds(330, 230, 40, 14);

        TabbedPane1.addTab("Alimentos", jPanel1);

        panel2.add(TabbedPane1);
        TabbedPane1.setBounds(0, 0, 720, 390);

        FinalizarC.setText("FINALIZAR COMPRA");
        FinalizarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarCActionPerformed(evt);
            }
        });
        panel2.add(FinalizarC);
        FinalizarC.setBounds(10, 360, 170, 20);

        getContentPane().add(panel2);
        panel2.setBounds(10, 5, 720, 390);

        panel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel3.setLayout(null);

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton5.setText("NUEVA COMPRA");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panel3.add(jButton5);
        jButton5.setBounds(240, 290, 180, 70);

        jButton6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton6.setText("VOLVER A LA TIENDA");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        panel3.add(jButton6);
        jButton6.setBounds(430, 290, 230, 70);

        jScrollPane3.setViewportView(producto);

        panel3.add(jScrollPane3);
        jScrollPane3.setBounds(20, 50, 100, 280);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Productos comprados");
        panel3.add(jLabel7);
        jLabel7.setBounds(10, 20, 140, 20);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("VALORTOTAL DE COMPRAS (Sin IVA)");
        panel3.add(jLabel8);
        jLabel8.setBounds(130, 100, 330, 22);
        panel3.add(Siniva);
        Siniva.setBounds(150, 130, 290, 40);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel12.setText("VALOR TOTAL A PAGAR");
        panel3.add(jLabel12);
        jLabel12.setBounds(140, 200, 300, 28);
        panel3.add(iva);
        iva.setBounds(490, 130, 120, 40);

        jLabel39.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel39.setText("IVA");
        panel3.add(jLabel39);
        jLabel39.setBounds(500, 90, 70, 28);
        panel3.add(Vtotal);
        Vtotal.setBounds(460, 190, 200, 40);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel3.add(jButton1);
        jButton1.setBounds(590, 400, 53, 23);

        getContentPane().add(panel3);
        panel3.setBounds(10, 5, 710, 380);

        panel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "SECCIÓN DEL VENDEDOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 24))); // NOI18N

        Clave.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Clave.setText("ACEPTAR");
        Clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClaveActionPerformed(evt);
            }
        });

        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });

        jLabel15.setText("USUARIO");

        jLabel16.setText("CONTRASEÑA");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setText("INSTRUCCIONES: POR FAVOR DIGITE EL USUARIO Y CONTRASEÑA PARA INGRESAR");

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel17)
                .addContainerGap(134, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Clave, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))
                        .addGap(64, 64, 64)
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(password))))
                .addGap(278, 278, 278))
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel17)
                .addGap(45, 45, 45)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(Clave, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        getContentPane().add(panel4);
        panel4.setBounds(10, 5, 710, 380);

        panel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "SECCIÓN DEL VENDEDOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 24))); // NOI18N

        jPanel2.setLayout(null);

        imProducto.setColumns(20);
        imProducto.setRows(5);
        jScrollPane1.setViewportView(imProducto);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 53, 664, 242);

        jTabbedPane2.addTab("PRODUCTOS", jPanel2);

        jLabel40.setText("total de dinero en ventas");

        jLabel41.setText("Moda del producto mas vendido");

        jLabel42.setText("Producto mas vendido");

        jLabel43.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel43.setText("Ventas");

        jLabel44.setText("Producto menos vendido");

        jLabel45.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel45.setText("Productos");

        reabastecer.setText("Reabastecer tienda");
        reabastecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reabastecerActionPerformed(evt);
            }
        });

        exit.setText("salir ");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        volver.setText("Volver a la tienda");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exit)
                .addGap(111, 111, 111))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(reabastecer, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volver))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jLabel45)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel42)
                                        .addGap(18, 18, 18)
                                        .addComponent(Mayor))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel44)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Menor, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel41)
                                    .addComponent(jLabel40))
                                .addGap(14, 14, 14)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Moda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel43))
                            .addComponent(TotalV, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(195, 195, 195))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(jLabel45))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(jLabel42)
                    .addComponent(Mayor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(jLabel44)
                    .addComponent(Menor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Moda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reabastecer)
                    .addComponent(volver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(exit)
                .addGap(33, 33, 33))
        );

        jTabbedPane2.addTab("ESTADISTICAS", jPanel5);

        javax.swing.GroupLayout panel5Layout = new javax.swing.GroupLayout(panel5);
        panel5.setLayout(panel5Layout);
        panel5Layout.setHorizontalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        panel5Layout.setVerticalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        getContentPane().add(panel5);
        panel5.setBounds(10, 5, 710, 380);

        setSize(new java.awt.Dimension(752, 430));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents



    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.panel3.setVisible(false);
        this.panel2.setVisible(true);
        TabbedPane1.setVisible(true);
        c=0;
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.panel3.setVisible(false);
        this.panel2.setVisible(false);
        this.panel1.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void ComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarActionPerformed
        this.panel3.setVisible(false);
        this.panel2.setVisible(true);
        this.panel1.setVisible(false);
        
    }//GEN-LAST:event_ComprarActionPerformed

    private void ScvendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScvendedorActionPerformed
        
        this.panel3.setVisible(false);
        this.panel2.setVisible(false);
        this.panel1.setVisible(false);
        this.panel4.setVisible(true);
         asignar();
         asignaciondeprec();
         asignacioniva();
         asignacionsiniva();
    }//GEN-LAST:event_ScvendedorActionPerformed

    private void ArrozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArrozActionPerformed
        Huevos.setSelected(false);
        Aceite.setSelected(false);
        Lentejas.setSelected(false);
        Leche.setSelected(false);
        Alimentos.setText("1300");
    }//GEN-LAST:event_ArrozActionPerformed

    private void HuevosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuevosActionPerformed
        Arroz.setSelected(false);
        Aceite.setSelected(false);
        Lentejas.setSelected(false);
        Leche.setSelected(false);
        Alimentos.setText("350");
    }//GEN-LAST:event_HuevosActionPerformed

    private void AceiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceiteActionPerformed
        Arroz.setSelected(false);
        Huevos.setSelected(false);
        Lentejas.setSelected(false);
        Leche.setSelected(false);
        Alimentos.setText("3500");
    }//GEN-LAST:event_AceiteActionPerformed

    private void LentejasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LentejasActionPerformed
        Arroz.setSelected(false);
        Huevos.setSelected(false);
        Aceite.setSelected(false);
        Leche.setSelected(false);
        Alimentos.setText("1700");
    }//GEN-LAST:event_LentejasActionPerformed

    private void LecheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LecheActionPerformed
        Arroz.setSelected(false);
        Huevos.setSelected(false);
        Aceite.setSelected(false);
        Lentejas.setSelected(false);
        Alimentos.setText("3200");
    }//GEN-LAST:event_LecheActionPerformed

    private void SarrozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SarrozActionPerformed
        for(int i=1;i<=5;i++){
            if(Sarroz.getSelectedIndex()==i){
                llenarlista.addElement(String.valueOf(i)+" Arroz Diana");
                GuardarP[c]=String.valueOf(i)+" Arroz Diana";
                GuardarV[c]=1300;
                Viva[c]=1300*0.04;
                Vsiniva[c]=1300*0.96;
                break;
            }
        }
        int h=Integer.parseInt(la1.getText());
        h=h-Sarroz.getSelectedIndex();
        la1.setText(""+h);
        this.JLista1.setModel(llenarlista);
            c=c+1;
    }//GEN-LAST:event_SarrozActionPerformed

    private void ShuevosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShuevosActionPerformed
        for(int i=1;i<=5;i++){
            if(Shuevos.getSelectedIndex()==i){
                llenarlista.addElement(String.valueOf(i)+" Huevos");
                GuardarP[c]=String.valueOf(i)+" Huevos";
                GuardarV[c]=350;
                Viva[c]=350*0.04;
                Vsiniva[c]=350*0.96;
                break;
            }
        }
        this.JLista1.setModel(llenarlista);
        int h=Integer.parseInt(la2.getText());
        h=h-Shuevos.getSelectedIndex();
        la2.setText(""+h);
        c=c+1;
    }//GEN-LAST:event_ShuevosActionPerformed

    private void SaceiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaceiteActionPerformed
        for(int i=1;i<=5;i++){
            if(Saceite.getSelectedIndex()==i){
                llenarlista.addElement(String.valueOf(i)+" Aceite Oliosoya");
                GuardarP[c]=String.valueOf(i)+" Aceite Oliosoya";
                GuardarV[c]=3500;
                Viva[c]=3500*0.04;
                Vsiniva[c]=3500*0.96;
                break;
            }
        }
        this.JLista1.setModel(llenarlista);
        int h=Integer.parseInt(la3.getText());
        h=h-Saceite.getSelectedIndex();
        la3.setText(""+h);
            c=c+1;
    }//GEN-LAST:event_SaceiteActionPerformed

    private void SlentejasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SlentejasActionPerformed
       for(int i=1;i<=5;i++){
           if(Slentejas.getSelectedIndex()==i){
           llenarlista.addElement(String.valueOf(i)+" Lentejas");
                GuardarP[c]=String.valueOf(i)+" Lentejas";
                GuardarV[c]=1700;
                Viva[c]=1700*0.04;
                Vsiniva[c]=1700*0.96;
                break;
            }
        }
        this.JLista1.setModel(llenarlista);
        int h=Integer.parseInt(la4.getText());
        h=h-Slentejas.getSelectedIndex();
        la4.setText(""+h);
            c=c+1;
        
    }//GEN-LAST:event_SlentejasActionPerformed

    private void SlecheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SlecheActionPerformed
        for(int i=1;i<=5;i++){
            if(Sleche.getSelectedIndex()==i){
                llenarlista.addElement(String.valueOf(i)+" Leche Alqueria");
                GuardarP[c]=String.valueOf(i)+" Leche Alqueria";
                GuardarV[c]=3200;
                Viva[c]=3200*0.04;
                Vsiniva[c]=3200*0.96;
                break;
            }
            
        }
        this.JLista1.setModel(llenarlista);
        int h=Integer.parseInt(la5.getText());
        h=h-Sleche.getSelectedIndex();
        la5.setText(""+h);
            c=c+1;
        
    }//GEN-LAST:event_SlecheActionPerformed

    private void DolexFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DolexFActionPerformed
        Pedialyte.setSelected(false);
        Acetaminofem.setSelected(false);
        DolexG.setSelected(false);
        VitaC.setSelected(false);
        Drogueria.setText("1200");
    }//GEN-LAST:event_DolexFActionPerformed

    private void PedialyteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedialyteActionPerformed
        DolexF.setSelected(false);
        Acetaminofem.setSelected(false);
        DolexG.setSelected(false);
        VitaC.setSelected(false);
        Drogueria.setText("7500");
    }//GEN-LAST:event_PedialyteActionPerformed

    private void AcetaminofemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcetaminofemActionPerformed
        DolexF.setSelected(false);
        Pedialyte.setSelected(false);
        DolexG.setSelected(false);
        VitaC.setSelected(false);
        Drogueria.setText("250");
    }//GEN-LAST:event_AcetaminofemActionPerformed

    private void DolexGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DolexGActionPerformed
        DolexF.setSelected(false);
        Pedialyte.setSelected(false);
        Acetaminofem.setSelected(false);
        VitaC.setSelected(false);
        Drogueria.setText("950");
    }//GEN-LAST:event_DolexGActionPerformed

    private void VitaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VitaCActionPerformed
        DolexF.setSelected(false);
        Pedialyte.setSelected(false);
        Acetaminofem.setSelected(false);
        DolexG.setSelected(false);
        Drogueria.setText("400");
    }//GEN-LAST:event_VitaCActionPerformed

    private void ClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClaveActionPerformed
        if("tienda".equals(usuario.getText())&&"udistrital".equals(password.getText())){
            panel4.setVisible(false);
            panel5.setVisible(true);
            productosA();
            ordenar();
        Mayor.setText(GuardarP[0].substring(1,GuardarP[0].length()));
        Menor.setText(GuardarP[c-1].substring(1,GuardarP[c-1].length()));
        Moda.setText(""+GuardarV[0]);
        double total=total();
        TotalV.setText(""+total);
        }else{
            JOptionPane.showMessageDialog(null, "El usuario y/o contraseña no son validos, por favor intente nuevamente");
            }
        
    }//GEN-LAST:event_ClaveActionPerformed

    private void BorrarP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarP1ActionPerformed
        
        int x = JLista1.getSelectedIndex();
        
        if (x >= 0) {
            String d = JLista1.getSelectedValue();
            String a = d.substring(2, d.length());
        for(int i=0;i<15;i++){
        if(a.equals(GuardarP[i])){
            for(int j=i;j<=13-i;j++){
                GuardarP[j]=GuardarP[j+1];
                GuardarV[j]=GuardarV[j+1];
                Viva[j]=Viva[j+1];
                Vsiniva[j]=Vsiniva[j+1];
            }
            break;
        }
    }
        
            llenarlista.remove(x);
            c=c-1;
    }else{
            JOptionPane.showMessageDialog(null, "No hay elementos en la lista o elemto seleccionado");
        }
    }//GEN-LAST:event_BorrarP1ActionPerformed

    private void SdolexfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SdolexfActionPerformed
        for(int i=1;i<=5;i++){
            if(Sdolexf.getSelectedIndex()==i){
                llenarlista2.addElement(String.valueOf(i)+" Dolex forte");
                GuardarP[c]=String.valueOf(i)+" Dolex forte";
                GuardarV[c]=1200;
                Viva[c]=1200*0.12;
                Vsiniva[c]=1200*0.88;
                break;
            }
            
        }
        
        this.JLista2.setModel(llenarlista2);
        int h=Integer.parseInt(la6.getText());
        h=h-Sdolexf.getSelectedIndex();
        la6.setText(""+h);
            c=c+1;
    }//GEN-LAST:event_SdolexfActionPerformed

    private void SpedialyteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpedialyteActionPerformed
        for(int i=1;i<=5;i++){
            if(Spedialyte.getSelectedIndex()==i){
                llenarlista2.addElement(String.valueOf(i)+" Pedialyte Max");
                GuardarP[c]=String.valueOf(i)+ "Peidalyte Max";
                GuardarV[c]=7500;
                Viva[c]=7500*0.12;
                Vsiniva[c]=7500*0.88;
                break;
            }
            
        }
        
        this.JLista2.setModel(llenarlista2);
        int h=Integer.parseInt(la7.getText());
        h=h-Spedialyte.getSelectedIndex();
        la7.setText(""+h);        
            c=c+1;
    }//GEN-LAST:event_SpedialyteActionPerformed

    private void SacetaminofemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SacetaminofemActionPerformed
        for(int i=1;i<=5;i++){
            if(Sacetaminofem.getSelectedIndex()==i){
                llenarlista2.addElement(String.valueOf(i)+" Acetaminofem");
                GuardarP[c]=String.valueOf(i)+" Acetaminofem";
                GuardarV[c]=250;
                Viva[c]=250*0.12;
                Vsiniva[c]=250*0.88;
                break;
            }
            
        }
        int h=Integer.parseInt(la8.getText());
        h=h-Sacetaminofem.getSelectedIndex();
        la8.setText(""+h);
        this.JLista2.setModel(llenarlista2);
            c=c+1;
    }//GEN-LAST:event_SacetaminofemActionPerformed

    private void SdolexgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SdolexgActionPerformed
        for(int i=1;i<=5;i++){
            if(Sdolexg.getSelectedIndex()==i){
                llenarlista2.addElement(String.valueOf(i)+" Dolex gripa");
                GuardarP[c]=String.valueOf(i)+" Dolex gripa";
                GuardarV[c]=950;
                Viva[c]=950*0.12;
                Vsiniva[c]=950*0.88;
                break;
            }
            
        }
        int h=Integer.parseInt(la9.getText());
        h=h-Sdolexg.getSelectedIndex();
        la9.setText(""+h);
        this.JLista2.setModel(llenarlista2);
            c=c+1;
    }//GEN-LAST:event_SdolexgActionPerformed

    private void SvitacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SvitacActionPerformed
        for(int i=1;i<=5;i++){
            if(Svitac.getSelectedIndex()==i){
                llenarlista2.addElement(String.valueOf(i)+" Vita C Mk");
                GuardarP[c]=String.valueOf(i)+" Vita C Mk";
                GuardarV[c]=400;
                Viva[c]=400*0.12;
                Vsiniva[c]=400*0.88;
                break;
            }
            
        }
        int h=Integer.parseInt(la10.getText());
        h=h-Svitac.getSelectedIndex();
        la10.setText(""+h);
        this.JLista2.setModel(llenarlista2);
            c=c+1;
    }//GEN-LAST:event_SvitacActionPerformed

    private void SjabondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SjabondActionPerformed
        for(int i=1;i<=5;i++){
            if(Sjabond.getSelectedIndex()==i){
                llenarlista3.addElement(String.valueOf(i)+" Jabon Dove");
                GuardarP[c]=String.valueOf(i)+" Jabon Dove";
                GuardarV[c]=3100;
                Viva[c]=3100*0.16;
                Vsiniva[c]=3100*0.84;
                break;
            }
            
        }
        int h=Integer.parseInt(la11.getText());
        h=h-Sjabond.getSelectedIndex();
        la11.setText(""+h);
        this.JLista3.setModel(llenarlista3);
            c=c+1;
    }//GEN-LAST:event_SjabondActionPerformed

    private void SdesodoranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SdesodoranteActionPerformed
        
        for(int i=1;i<=5;i++){
            if(Sdesodorante.getSelectedIndex()==i){
                llenarlista3.addElement(String.valueOf(i)+" Desodorante Balance");
                GuardarP[c]=String.valueOf(i)+" Desodorante Balance";
                GuardarV[c]=2650;
                Viva[c]=2650*0.16;
                Vsiniva[c]=2650*0.84;
                break;
            }
            
        }
        int h=Integer.parseInt(la12.getText());
        h=h-Sdesodorante.getSelectedIndex();
        la12.setText(""+h);
        this.JLista3.setModel(llenarlista3);
            c=c+1;
    }//GEN-LAST:event_SdesodoranteActionPerformed

    private void ScepilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScepilloActionPerformed
        for(int i=1;i<=5;i++){
            if(Scepillo.getSelectedIndex()==i){
                llenarlista3.addElement(String.valueOf(i)+" Cepillo dental");
                GuardarP[c]=String.valueOf(i)+" Cepillo dental";
                GuardarV[c]=2000;
                Viva[c]=2000*0.16;
                Vsiniva[c]=2000*0.84;
                break;
            }
            
        }
        int h=Integer.parseInt(la13.getText());
        h=h-Scepillo.getSelectedIndex();
        la13.setText(""+h);
        this.JLista3.setModel(llenarlista3);
            c=c+1;
    }//GEN-LAST:event_ScepilloActionPerformed

    private void SjabonfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SjabonfActionPerformed
        for(int i=1;i<=5;i++){
            if(Sjabonf.getSelectedIndex()==i){
                llenarlista3.addElement(String.valueOf(i)+" Jabon Fab");
                GuardarP[c]=String.valueOf(i)+" Jabon Fab";
                GuardarV[c]=3400;
                Viva[c]=3400*0.16;
                Vsiniva[c]=3400*0.84;
                break;
            }
            
        }
        int h=Integer.parseInt(la14.getText());
        h=h-Sjabonf.getSelectedIndex();
        la14.setText(""+h);
        this.JLista3.setModel(llenarlista3);
            c=c+1;
    }//GEN-LAST:event_SjabonfActionPerformed

    private void ScremaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScremaActionPerformed
        for(int i=1;i<=5;i++){
            if(Screma.getSelectedIndex()==i){
                llenarlista3.addElement(String.valueOf(i)+" Crema dental Colgate");
                GuardarP[c]=String.valueOf(i)+" Crema dental Colgate";
                GuardarV[c]=2500;
                Viva[c]=3500*0.16;
                Vsiniva[c]=3500*0.84;
                break;
            }
            
        }
        int h=Integer.parseInt(la15.getText());
        h=h-Screma.getSelectedIndex();
        la15.setText(""+h);
        this.JLista3.setModel(llenarlista3);
            c=c+1;
    }//GEN-LAST:event_ScremaActionPerformed

    private void BorrarP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarP3ActionPerformed
       
       int x= JLista3.getSelectedIndex();
       
       if (x >= 0) {
            String d = JLista3.getSelectedValue();
            String a = d.substring(2, d.length());
             
            for(int i=0;i<15;i++){
                if(a.equals(GuardarP[i])){
                    for(int j=i;j<=13-i;j++){
                        GuardarP[j]=GuardarP[j+1];
                        GuardarV[j]=GuardarV[j+1];
                        Viva[j]=Viva[j+1];
                        Vsiniva[j]=Vsiniva[j+1];
                    }
                    break;
                }
    }
        
            llenarlista3.remove(x);
            c=c-1;
    }else{
            JOptionPane.showMessageDialog(null, "No hay elementos en la lista o elemto seleccionado");
        }
    }//GEN-LAST:event_BorrarP3ActionPerformed

    private void BorrarP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarP2ActionPerformed
        
        int x = JLista2.getSelectedIndex();
        
        if (x >= 0) {
            String d = JLista2.getSelectedValue();
            String a = d.substring(2, d.length());
        for(int i=0;i<15;i++){
        if(a.equals(GuardarP[i])){
            for(int j=i;j<=13-i;j++){
                GuardarP[j]=GuardarP[j+1];
                GuardarV[j]=GuardarV[j+1];
                Viva[j]=Viva[j+1];
                Vsiniva[j]=Vsiniva[j+1];
            }
            break;
        }
    }
        
            llenarlista2.remove(x);
            c=c-1;
    }else{
            JOptionPane.showMessageDialog(null, "No hay elementos en la lista o elemto seleccionado");
        }
    }//GEN-LAST:event_BorrarP2ActionPerformed

    private void FinalizarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarCActionPerformed
        this.panel2.setVisible(false);
        this.panel3.setVisible(true);
        imprimir();
        double f,d, total;
        f=siniva();
        Siniva.setText(String.valueOf(f));
        d=iva();
        iva.setText(String.valueOf(d));
        total=total();
        Vtotal.setText(String.valueOf(total));
        
    }//GEN-LAST:event_FinalizarCActionPerformed

    private void reabastecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reabastecerActionPerformed
        c=0;
        la1.setText(""+20);la2.setText(""+20);la3.setText(""+20);la4.setText(""+20);la5.setText(""+20);
        la6.setText(""+20);la7.setText(""+20);la8.setText(""+20);la9.setText(""+20);la10.setText(""+20);
        la11.setText(""+20);la12.setText(""+20);la13.setText(""+20);la14.setText(""+20);la15.setText(""+20);
    }//GEN-LAST:event_reabastecerActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    private void CremaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CremaActionPerformed
        JabonD.setSelected(false);
        Desodorante.setSelected(false);
        Cepillo.setSelected(false);
        JabonF.setSelected(false);
        Aseo.setText("2500");
    }//GEN-LAST:event_CremaActionPerformed

    private void JabonFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JabonFActionPerformed
        JabonD.setSelected(false);
        Desodorante.setSelected(false);
        Cepillo.setSelected(false);
        Crema.setSelected(false);
        Aseo.setText("3400");
    }//GEN-LAST:event_JabonFActionPerformed

    private void CepilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CepilloActionPerformed
        JabonD.setSelected(false);
        Desodorante.setSelected(false);
        JabonF.setSelected(false);
        Crema.setSelected(false);
        Aseo.setText("2000");
    }//GEN-LAST:event_CepilloActionPerformed

    private void DesodoranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesodoranteActionPerformed
        JabonD.setSelected(false);
        Cepillo.setSelected(false);
        JabonF.setSelected(false);
        Crema.setSelected(false);
        Aseo.setText("2650");
    }//GEN-LAST:event_DesodoranteActionPerformed

    private void JabonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JabonDActionPerformed
        Desodorante.setSelected(false);
        Cepillo.setSelected(false);
        JabonF.setSelected(false);
        Crema.setSelected(false);
        Aseo.setText("3100");
    }//GEN-LAST:event_JabonDActionPerformed
    void asignar(){
vector[0] ="Arroz Diana"; vector[1] ="Huevos"; vector[2] ="Aceite Oliosoya"; vector[3] ="Lentejas";
vector[4] ="Leche Alqueria";vector[5] ="Dolex forte";vector[6] ="Pedialyte Max";
vector[7] ="Acetaminofem";vector[8] ="Dolex Gripa";vector[9] ="Vita C Mk";vector[10] ="Jabon Dove";
vector[11] ="Desodorante Balance";vector[12] ="Cepillo Dental";vector[13] ="Jabon Fab";vector[14] ="Crema Dental Colgate";
}
void asignaciondeprec(){
vectorprec[0]=1300;vectorprec[1]=350;vectorprec[2]=3500;vectorprec[3]=1700;vectorprec[4]=3200;
vectorprec[5]=1200;vectorprec[6]=7500;vectorprec[7]=250;vectorprec[8]=950;vectorprec[9] =400;
vectorprec[10]=3100;vectorprec[11]=2650;vectorprec[12]=2000;vectorprec[13]=3500;vectorprec[14]=3400;
}

void asignacioniva(){
  Iva[0]=1300*.04;Iva[1]=350*.04;Iva[2]=3500*.04;Iva[3]=1700*.04;Iva[4]=3200*.04;
  Iva[5]=1200*.12;Iva[6]=7500*.12;Iva[7]=250*.12;Iva[8]=950*.12;Iva[9]=400*.12;
  Iva[10]=3100*.16;Iva[11]=2650*.16;Iva[12]=2000*.16;Iva[13]=3500*.16;Iva[14]=3400*.16;  
}
void asignacionsiniva(){
    SinIva[0]=1300*.96;SinIva[1]=350*.96;SinIva[2]=3500*.96;SinIva[3]=1700*.96;SinIva[4]=3200*.96;
  SinIva[5]=1200*.88;SinIva[6]=7500*.88;SinIva[7]=250*.88;SinIva[8]=950*.88;SinIva[9]=400*.88;
  SinIva[10]=3100*.84;SinIva[11]=2650*.84;SinIva[12]=2000*.84;SinIva[13]=3500*.84;SinIva[14]=3400*.84;
}
    void imprimir(){
       for(int i=0;i<=c;i++){
        this.Producto.addElement(GuardarP[i]);
        producto.setModel(Producto);
       }
    }
    double siniva(){
        double f = 0,a;
        for(int i=0;i<=c;i++){
            a=Vsiniva[i];
            f=f+a;
       }
        return f;
    }
    double iva(){
        double f = 0,a;
        for(int i=0;i<=c;i++){
            a=Viva[i];
            f=f+a;
        }
        return f;
    }
    double total(){
        double f = 0,a;
        for(int i=0;i<=c;i++){
            a=GuardarV[i];
            f=f+a;
        }
        return f;
    }
    void productosA(){
        for(int i=0;i<15;i++){
            if(i<=4){
            imProducto.setText(imProducto.getText()+vector[i]+": "
                    +String.valueOf(vectorprec[i])+"  "
                    + "iva: 4% " + String.valueOf(Iva[i])
                    + "  "+ String.valueOf(SinIva[i])+ "\n" );
            }else if(i<=9){
                imProducto.setText(imProducto.getText()+vector[i]+": "
                    +String.valueOf(vectorprec[i])+"  "
                    + "iva: 12% " + String.valueOf(Iva[i])
                    + "  "+ String.valueOf(SinIva[i])+"\n" );
            }else{
                imProducto.setText(imProducto.getText()+vector[i]+": "
                    +String.valueOf(vectorprec[i])+"  "
                    + "iva: 16% " + String.valueOf(Iva[i])
                    + "  "+ String.valueOf(SinIva[i])+"\n" );
            }
        }
    }
        void ordenar(){
            String aux;
            int aux2;
            for(int i=0;i<=c-1;i++){
                for(int j=0;j<=c-i-2;j++){
                    if (GuardarP[j + 1].charAt(0) > GuardarP[j].charAt(0)) {
                    aux = GuardarP[j + 1];
                    aux2=GuardarV[j+1];
                    GuardarP[j + 1] = GuardarP[j];
                    GuardarV[j + 1] = GuardarV[j];
                    GuardarP[j] = aux;
                    GuardarV[j] = aux2;
                }
                }
            }
        }



    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tiendav().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Aceite;
    private javax.swing.JCheckBox Acetaminofem;
    private javax.swing.JLabel Alimentos;
    private javax.swing.JCheckBox Arroz;
    private javax.swing.JLabel Aseo;
    private javax.swing.JButton BorrarP1;
    private javax.swing.JButton BorrarP2;
    private javax.swing.JButton BorrarP3;
    private javax.swing.JCheckBox Cepillo;
    private javax.swing.JButton Clave;
    private javax.swing.JButton Comprar;
    private javax.swing.JCheckBox Crema;
    private javax.swing.JCheckBox Desodorante;
    private javax.swing.JCheckBox DolexF;
    private javax.swing.JCheckBox DolexG;
    private javax.swing.JLabel Drogueria;
    private javax.swing.JButton FinalC;
    private javax.swing.JButton FinalizarC;
    private javax.swing.JCheckBox Huevos;
    private javax.swing.JList<String> JLista1;
    private javax.swing.JList<String> JLista2;
    private javax.swing.JList<String> JLista3;
    private javax.swing.JCheckBox JabonD;
    private javax.swing.JCheckBox JabonF;
    private javax.swing.JCheckBox Leche;
    private javax.swing.JCheckBox Lentejas;
    private javax.swing.JTextField Mayor;
    private javax.swing.JTextField Menor;
    private javax.swing.JTextField Moda;
    private javax.swing.JCheckBox Pedialyte;
    private javax.swing.JComboBox<String> Saceite;
    private javax.swing.JComboBox<String> Sacetaminofem;
    private javax.swing.JComboBox<String> Sarroz;
    private javax.swing.JComboBox<String> Scepillo;
    private javax.swing.JComboBox<String> Screma;
    private javax.swing.JButton Scvendedor;
    private javax.swing.JComboBox<String> Sdesodorante;
    private javax.swing.JComboBox<String> Sdolexf;
    private javax.swing.JComboBox<String> Sdolexg;
    private javax.swing.JComboBox<String> Shuevos;
    private javax.swing.JTextField Siniva;
    private javax.swing.JComboBox<String> Sjabond;
    private javax.swing.JComboBox<String> Sjabonf;
    private javax.swing.JComboBox<String> Sleche;
    private javax.swing.JComboBox<String> Slentejas;
    private javax.swing.JComboBox<String> Spedialyte;
    private javax.swing.JComboBox<String> Svitac;
    private javax.swing.JTabbedPane TabbedPane1;
    private javax.swing.JTextField TotalV;
    private javax.swing.JCheckBox VitaC;
    private javax.swing.JTextField Vtotal;
    private javax.swing.JButton exit;
    private javax.swing.JTextArea imProducto;
    private javax.swing.JTextField iva;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel la1;
    private javax.swing.JLabel la10;
    private javax.swing.JLabel la11;
    private javax.swing.JLabel la12;
    private javax.swing.JLabel la13;
    private javax.swing.JLabel la14;
    private javax.swing.JLabel la15;
    private javax.swing.JLabel la2;
    private javax.swing.JLabel la3;
    private javax.swing.JLabel la4;
    private javax.swing.JLabel la5;
    private javax.swing.JLabel la6;
    private javax.swing.JLabel la7;
    private javax.swing.JLabel la8;
    private javax.swing.JLabel la9;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel4;
    private javax.swing.JPanel panel5;
    private javax.swing.JPasswordField password;
    private javax.swing.JList<String> producto;
    private javax.swing.JButton reabastecer;
    private javax.swing.JTextField usuario;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}